[global]
interfaces = lo
bind interfaces only = yes
map to guest = never
log file = /tmp/transume-smbd.log
pid directory = /run/samba
lock directory = /run/samba
state directory = /var/lib/samba
cache directory = /var/cache/samba

[transume]
path = /home/partimag/transume-smb-server
read only = no
valid users = live
